#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: Batch Processing for YouTube Playlists & Video Lists

set -e

echo "========================================"
echo "Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo -e "${YELLOW}Installing Python dependencies...${NC}"

# Check if pip is available
if ! command -v pip &> /dev/null; then
    echo -e "${RED}pip not found. Please install Python and pip.${NC}"
    exit 1
fi

# Install dependencies
pip install -r requirements.txt

# Verify new dependencies
echo ""
echo -e "${YELLOW}Verifying new dependencies...${NC}"
python -c "from pytubefix import Playlist; from tqdm import tqdm; print('✅ pytubefix and tqdm installed successfully')" || {
    echo -e "${RED}Failed to import new dependencies${NC}"
    exit 1
}

# ============================================
# ENVIRONMENT READY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "This is a single-file CLI tool - no services to start."
echo ""
echo "Test the tool:"
echo "  python yt_transcript.py VIDEO_ID"
echo ""
echo "New batch modes (after implementation):"
echo "  python yt_transcript.py --playlist 'https://youtube.com/playlist?list=PLAYLIST_ID'"
echo "  python yt_transcript.py --file urls.txt --parallel 5"
echo "  python yt_transcript.py VIDEO_ID1 VIDEO_ID2 VIDEO_ID3"
echo ""
